export default {
  uk: {"grantTitle":"Видати підписку","userId":"ID користувача","plan":"План","selectPlan":"Оберіть план","days":"Днів","notes":"Нотатки","notesPlaceholder":"Тест, промо тощо.","grant":"Видати","grantSuccess":"Підписку видано!","fillAll":"Заповніть усі поля","error":"Помилка","allSubs":"Усі підписки","filterPlaceholder":"Фільтр за email або планом...","user":"Email","status":"Статус","started":"Початок","expires":"Закінчується","grantedBy":"Джерело","admin":"Адмін","payment":"Оплата"},
  en: { grantTitle: 'Grant subscription', userId: 'User ID', plan: 'Plan', selectPlan: 'Select plan', days: 'Days', notes: 'Notes', notesPlaceholder: 'Test, promo, etc.', grant: 'Grant', grantSuccess: 'Subscription granted!', fillAll: 'Fill all fields', error: 'Error', allSubs: 'All subscriptions', filterPlaceholder: 'Filter by email or plan...', user: 'Email', status: 'Status', started: 'Started', expires: 'Expires', grantedBy: 'Source', admin: 'Admin', payment: 'Payment' },
  ru: { grantTitle: 'Выдать подписку', userId: 'ID пользователя', plan: 'Тариф', selectPlan: 'Выберите тариф', days: 'Дней', notes: 'Примечание', notesPlaceholder: 'Тест, промо и т.д.', grant: 'Выдать', grantSuccess: 'Подписка выдана!', fillAll: 'Заполните все поля', error: 'Ошибка', allSubs: 'Все подписки', filterPlaceholder: 'Фильтр по email или тарифу...', user: 'Email', status: 'Статус', started: 'Начало', expires: 'Истекает', grantedBy: 'Источник', admin: 'Админ', payment: 'Оплата' },
  de: { grantTitle: 'Abonnement gewähren', userId: 'Benutzer-ID', plan: 'Tarif', selectPlan: 'Tarif wählen', days: 'Tage', notes: 'Hinweis', notesPlaceholder: 'Test, Promo usw.', grant: 'Gewähren', grantSuccess: 'Abonnement gewährt!', fillAll: 'Alle Felder ausfüllen', error: 'Fehler', allSubs: 'Alle Abonnements', filterPlaceholder: 'Nach E-Mail oder Tarif filtern...', user: 'E-Mail', status: 'Status', started: 'Beginn', expires: 'Läuft ab', grantedBy: 'Quelle', admin: 'Admin', payment: 'Zahlung' },
  es: { grantTitle: 'Conceder suscripción', userId: 'ID de usuario', plan: 'Plan', selectPlan: 'Selecciona un plan', days: 'Días', notes: 'Notas', notesPlaceholder: 'Prueba, promo, etc.', grant: 'Conceder', grantSuccess: '¡Suscripción concedida!', fillAll: 'Rellena todos los campos', error: 'Error', allSubs: 'Todas las suscripciones', filterPlaceholder: 'Filtrar por email o plan...', user: 'Email', status: 'Estado', started: 'Inicio', expires: 'Expira', grantedBy: 'Origen', admin: 'Admin', payment: 'Pago' },
  it: { grantTitle: 'Concedi abbonamento', userId: 'ID utente', plan: 'Piano', selectPlan: 'Seleziona un piano', days: 'Giorni', notes: 'Note', notesPlaceholder: 'Test, promo, ecc.', grant: 'Concedi', grantSuccess: 'Abbonamento concesso!', fillAll: 'Compila tutti i campi', error: 'Errore', allSubs: 'Tutti gli abbonamenti', filterPlaceholder: 'Filtra per email o piano...', user: 'Email', status: 'Stato', started: 'Inizio', expires: 'Scade', grantedBy: 'Origine', admin: 'Admin', payment: 'Pagamento' },
  pt: { grantTitle: 'Conceder assinatura', userId: 'ID do usuário', plan: 'Plano', selectPlan: 'Selecione um plano', days: 'Dias', notes: 'Observação', notesPlaceholder: 'Teste, promo, etc.', grant: 'Conceder', grantSuccess: 'Assinatura concedida!', fillAll: 'Preencha todos os campos', error: 'Erro', allSubs: 'Todas as assinaturas', filterPlaceholder: 'Filtrar por email ou plano...', user: 'Email', status: 'Status', started: 'Início', expires: 'Expira', grantedBy: 'Origem', admin: 'Admin', payment: 'Pagamento' },
  zh: { grantTitle: '发放订阅', userId: '用户 ID', plan: '套餐', selectPlan: '选择套餐', days: '天数', notes: '备注', notesPlaceholder: '测试、促销等', grant: '发放', grantSuccess: '订阅已发放！', fillAll: '请填写所有字段', error: '错误', allSubs: '全部订阅', filterPlaceholder: '按邮箱或套餐筛选……', user: '邮箱', status: '状态', started: '开始', expires: '到期', grantedBy: '来源', admin: '管理员', payment: '付款' },
  ar: { grantTitle: 'منح اشتراك', userId: 'معرّف المستخدم', plan: 'الباقة', selectPlan: 'اختر باقة', days: 'أيام', notes: 'ملاحظة', notesPlaceholder: 'اختبار، عرض، إلخ.', grant: 'منح', grantSuccess: 'تم منح الاشتراك!', fillAll: 'املأ جميع الحقول', error: 'خطأ', allSubs: 'جميع الاشتراكات', filterPlaceholder: 'التصفية حسب البريد أو الباقة...', user: 'البريد الإلكتروني', status: 'الحالة', started: 'البداية', expires: 'ينتهي', grantedBy: 'المصدر', admin: 'مشرف', payment: 'الدفع' },
}
